version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cv-service
    restart: unless-stopped
    networks:
      - mon-network
    ports:
      - "6060:6000"
    depends_on:
      - db
  db:
    image: postgres
    container_name: cv_pgdb
    restart: unless-stopped
    environment:
      POSTGRES_USER: user-name
      POSTGRES_PASSWORD: strong-password
      POSTGRES_DB: user_db
    networks:
      - mon-network
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: cv-pgadmin4
    restart: unless-stopped
    ports:
      - "8887:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - mon-network
    depends_on:
      - db

volumes:
  local_pgdata:
  pgadmin-data:

networks:
  mon-network:
    driver: bridge
